language: node_js
node_js:
  - "4"

install:
  - npm install

cache:
  directories:
    - node_modules

script: npm run build

branches:
  only:
    - master

env:
  global:
    - NODE_ENV=production

